### ISSUE TITLE
Need to add cran mirror to apt-get sources

### ISSUE THREAD

**Issue by jhwhite** [chrisrzhou/RShiny-EC2Bootstrap#1]
At least for me, `sudo apt-get install r-base-dev` didn't work. I had to run `sudo add-apt-repository http://cran.cnr.Berkeley.edu/` Then `sudo apt-get update` then I could execute `sudo apt-get install r-base-dev`.

**Comment by chrisrzhou** [comment]
Hey thanks.  I didn't run into the problem on my EC2 instance.  Are you using Ubuntu 14.04 on AWS or some other version?  Mine came with the R repository by default I think.
